defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: kaggle-learning-agency-lab-automated-essay-scoring-2
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

voted_logit: ${connected_dir}/logits/${voted_name}.npy
submission_file: ${connected_dir}/data/test.csv
data_column_name: full_text
target_column_name: score
voted_file: ${connected_dir}/submissions/${voted_name}.csv

votings:
  logit1: 0.5
  logit2: 0.5